//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyOLD
    {
        public int recNum { get; set; }
        public string day_of_week { get; set; }
        public Nullable<int> food1 { get; set; }
        public Nullable<float> qty1 { get; set; }
        public Nullable<int> food2 { get; set; }
        public Nullable<float> qty2 { get; set; }
        public Nullable<int> food3 { get; set; }
        public Nullable<float> qty3 { get; set; }
        public Nullable<int> food4 { get; set; }
        public Nullable<float> qty4 { get; set; }
        public Nullable<int> food5 { get; set; }
        public Nullable<float> qty5 { get; set; }
        public Nullable<int> food6 { get; set; }
        public Nullable<float> qty6 { get; set; }
        public Nullable<int> food7 { get; set; }
        public Nullable<float> qty7 { get; set; }
        public Nullable<int> food8 { get; set; }
        public Nullable<float> qty8 { get; set; }
        public Nullable<int> food9 { get; set; }
        public Nullable<float> qty9 { get; set; }
        public Nullable<int> food10 { get; set; }
        public Nullable<float> qty10 { get; set; }
    }
}
