//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMeal
    {
        public int key { get; set; }
        public Nullable<int> recNum { get; set; }
        public Nullable<System.DateTime> dayDate { get; set; }
        public Nullable<int> food { get; set; }
        public Nullable<float> quantity { get; set; }
    }
}
