//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int recNum { get; set; }
        public string food1 { get; set; }
        public Nullable<int> calories { get; set; }
    }
}
