//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string name { get; set; }
        public Nullable<float> height { get; set; }
        public Nullable<float> initialWeight { get; set; }
        public Nullable<float> targetWeight { get; set; }
        public string SSID { get; set; }
    }
}
